FROM quay.io/toolbx-images/ubuntu-toolbox:latest

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience" \
      maintainer="david@davidleal.com"

RUN apt-get --assume-yes update && \
    apt-get --assume-yes dist-upgrade && \
    apt-get --assume-yes install --no-install-recommends build-essential git

ENV USER_ID=1111

RUN useradd -u "${USER_ID}" --create-home --shell /bin/bash --user-group linuxbrew && \
    echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers && \
    su - linuxbrew -c 'mkdir ~/.linuxbrew'

ENV NONINTERACTIVE=1 
USER linuxbrew

RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
